[tool.poetry]
name = "seedcase-sprout"
version = "0.0.1"
description = "Grow your research data in a structured, modern way that follows best practices."
authors = [
  "Luke W. Johnston <lwjohnst@gmail.com>",
  "Henrik Goul <hgo@mjolner.dk>",
  "Kristiane Beicher <kris.beicher@clin.au.dk>", 
  "Philip Christiansen <pch@mjolner.dk>",
  "Signe Kirk Brødbæk <signekb@clin.au.dk>",
]
maintainers = [
  "Luke W. Johnston <lwjohnst@gmail.com>",
  "Kristiane Beicher <kris.beicher@clin.au.dk>", 
  "Signe Kirk Brødbæk <signekb@clin.au.dk>",
]
readme = "README.md"
homepage = "https://sprout.seedcase-project.org"
repository = "https://github.com/seedcase-project/seedcase-sprout"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/seedcase-project/seedcase-sprout/issues"

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.8"
ruff = "^0.1.9"
whitenoise = "^6.6.0"
gunicorn = "^21.2.0"
dj-database-url = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
