name: Deploy Images to Github Container registry

on:
  push:

jobs:
  push-store-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add semantic version tag, Disabled
        if: false
        id: semanticVersion
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: github.ref != 'refs/heads/main'
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN}}
      - name: Get date for image version
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and publish image'
        run: |
          docker build . --tag local-seedcase-sprout
          docker tag local-seedcase-sprout ghcr.io/seedcase-project/seedcase-sprout:${{ steps.date.outputs.date }}-${GITHUB_SHA::7}
          docker push ghcr.io/seedcase-project/seedcase-sprout:v${{ steps.date.outputs.date }}-${GITHUB_SHA::7}
      - name: 'Release'
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag local-seedcase-sprout ghcr.io/seedcase-project/seedcase-sprout:${{ steps.date.outputs.date }}
          docker push local-seedcase-sprout ghcr.io/seedcase-project/seedcase-sprout:${{ steps.date.outputs.date }}
