name: Deploy Images to Github Container registry

# Actions are triggered on: push to main branch, pull requests targeting the main branch and manual triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add semantic version tag
        id: semanticVersion
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN}}
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and publish image with 0.1.0'
        run: |
          docker build . --tag ghcr.io/seedcase-project/seedcase-sprout:${{ steps.semanticVersion.outputs.tag }}-prerelease-${GITHUB_SHA::7}
          docker push ghcr.io/seedcase-project/seedcase-sprout:${{ steps.semanticVersion.outputs.tag }}-prerelease-${GITHUB_SHA::7}
      - name: 'Release by tagging prerelease'
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/seedcase-project/seedcase-sprout:${{ steps.semanticVersion.outputs.tag }}-prerelease-${GITHUB_SHA::7} ghcr.io/seedcase-project/seedcase-sprout:${{ steps.semanticVersion.outputs.tag }}
          docker push local-seedcase-sprout ghcr.io/seedcase-project/seedcase-sprout:${{ steps.semanticVersion.outputs.tag }}
